@startuml

'
' SPDX-License-Identifier: EPL-2.0
'
' An architecture model of SW360antenna
'

skinparam componentStyle uml2

' Antenna Product Components

node "Core" {
    component [model] as model
    component [runtime] as runtime
    component [core-workflow-steps] as core_workflow_steps
    component [model-testing] as model_testing
}

node "Frontend Stubs" {
    component [cli-frontend-stub] as cli_stub
    component [maven-frontend-stub] as maven_stub
    component [gradle-frontend-stub] as gradle_stub
    component [frontend-stubs-testing] as frontend_testing
}

component [maven-module] as maven_module
component [sw360-module] as sw360_module
component [ort-module] as ort_module
component [spdx-license-knowledge-base] as spdx_kb
component [csv-license-knowledge-base)] as csv_lic_kb

node "Validators" {
    component [drools-checker] as drools_checker
    component [rule-engine-testing] as drools_testing
    component [common-rules] as common_rules
    component [simple-validators-module] as simple_validators
}

node "P2" {
    component [antenna-p2-enricher] as p2_enricher
}

node "Frontend" {
    component [configuration] as base_config
    component [cli] as cli
    component [maven-plugin] as maven_plugin
    component [gradle-plugin] as gradle_plugin
    component [documentation] as docu
}

' Tina Components

node "Tina" {
  component [tina-bdp] as bdp <<Tina, obsolete>>
  component [tina-clm] as iq <<Tina>>
  component [tina-javascript] as javascript <<Tina>>
  component [tina-simple-rule-engine] as simple_rule_engine <<Tina, obsolete>>
  component [osm-tina-drools-engine] as drools_engine <<Tina, obsolete>>

  node "Bosch Docu Generator" {
    component [abstract-tina-pdf-report-generator] as base_pdf_generator <<Tina, obsolete>>
    component [osm-tina-bosch-disclosure-document] as legal_generator <<Tina, obsolete>>
  }

  component [Bosch License Knowledge Base (tina-knowledge-base)] as bosch_lic_kb <<Tina>>

  node "Bosch Frontend" {
    component [tina-bosch-configuration] as bosch_base_config <<Tina>>
    component [tina-bosch-cli] as bosch_cli <<Tina>>
    component [tina-bosch-mojo] as bosch_maven_plugin <<Tina>>
    component [tina-bosch-gradle-plugin] as bosch_gradle_plugin <<Tina>>

    component [tina-documentation] as tina_docu <<Tina>>
  }

  component [tina-bosch-example-projects] as tina_testing <<Tina>>
}

' Layout

maven_module -[hidden]- runtime
sw360_module -[hidden]- runtime
drools_checker -[hidden]- runtime
p2_enricher -[hidden]- runtime
ort_module -[hidden]- runtime
spdx_kb -[hidden]- runtime
csv_lic_kb -[hidden]- runtime

cli_stub -[hidden]- maven_module
cli_stub -[hidden]- sw360_module
cli_stub -[hidden]- drools_checker
cli_stub -[hidden]- p2_enricher
cli_stub -[hidden]- ort_module
cli_stub -[hidden]- spdx_kb
cli_stub -[hidden]- csv_lic_kb

base_config -[hidden]- cli_stub
bosch_base_config -[hidden]- cli_stub

' Dependencies Antenna

model_testing --> model

runtime --> model

runtime ..> model_testing : test

core_workflow_steps --> model

core_workflow_steps --> runtime

core_workflow_steps ..> model_testing : test

cli_stub --> model

cli_stub --> runtime

maven_stub --> model

maven_stub --> runtime

gradle_stub --> model

gradle_stub --> runtime

frontend_testing --> model

frontend_testing --> model_testing

frontend_testing --> cli_stub

frontend_testing --> maven_stub

frontend_testing --> gradle_stub

maven_module --> model

maven_module --> runtime

maven_module ..> model_testing : test

sw360_module --> model

sw360_module --> runtime

sw360_module ..> model_testing : test

drools_checker --> model

drools_checker --> runtime

drools_testing --> model

drools_testing --> drools_checker

simple_validators --> model

simple_validators --> runtime

simple_validators ..> model_testing : test

p2_enricher --> model

p2_enricher --> runtime

p2_enricher ..> model_testing : test

ort_module --> model

ort_module --> runtime

common_rules --> model

common_rules ..> drools_testing

spdx_kb --> model

base_config -->  core_workflow_steps

base_config --> common_rules

base_config --> maven_module

base_config --> ort_module

base_config --> drools_checker

base_config --> spdx_kb

base_config --> p2_enricher

base_config --> simple_validators

base_config --> sw360_module

base_config ..> model_testing : test

cli --> cli_stub

cli --> base_config

cli ..> frontend_testing : test

maven_plugin --> maven_stub

maven_plugin --> base_config

maven_plugin ..> frontend_testing : test

gradle_plugin --> gradle_stub

gradle_plugin --> base_config

gradle_plugin ..> frontend_testing : test

csv_lic_kb --> model

' Tina Dependencies

bdp --> model : tina

bdp ..> model_testing : test

iq --> model : tina

iq --> runtime : tina

iq --> core_workflow_steps : tina

iq ..> model_testing : test

javascript --> model : tina

javascript --> core_workflow_steps : tina

simple_rule_engine --> model : tina

simple_rule_engine --> core_workflow_steps : tina

drools_engine --> model : tina

drools_engine --> core_workflow_steps : tina

base_pdf_generator --> model : tina

base_pdf_generator --> runtime : tina

base_pdf_generator ..> model_testing : test

legal_generator --> model : tina

legal_generator --> runtime : tina

legal_generator --> base_pdf_generator : tina

legal_generator ..> model_testing : test

bosch_base_config --> model : tina

bosch_base_config --> csv_lic_kb : tina

bosch_base_config --> bosch_lic_kb : tina

bosch_base_config --> core_workflow_steps : tina

bosch_base_config --> maven_module : tina

bosch_base_config --> simple_validators : tina

bosch_base_config --> iq : tina

bosch_base_config --> javascript : tina

bosch_base_config --> drools_engine : tina

bosch_base_config --> p2_enricher : tina

bosch_base_config --> sw360_module : tina

bosch_base_config --> common_rules : tina

bosch_base_config --> legal_generator : tina

bosch_base_config ..> model_testing : test

bosch_cli --> cli_stub : tina

bosch_cli --> bosch_base_config : tina

bosch_maven_plugin --> maven_stub : tina

bosch_maven_plugin --> bosch_base_config : tina

bosch_maven_plugin ..> frontend_testing : test

bosch_gradle_plugin --> gradle_stub : tina

bosch_gradle_plugin --> bosch_base_config : tina

bosch_gradle_plugin ..> frontend_testing : test

bosch_gradle_plugin ..> tina_testing : test

tina_testing --> frontend_testing : tina

@enduml
