# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright (c) Bosch Software Innovations GmbH 2019.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# SPDX-License-Identifier: EPL-2.0

$provision = <<SCRIPT
set -ex
apt-get update
apt-get install -yqq openjdk-8-jdk openjdk-8-demo openjdk-8-doc openjdk-8-jre-headless openjdk-8-source \
    maven \
    gradle \
    git
SCRIPT

$runCleanup = <<SCRIPT
rm -rf ~/.m2/repository/org/eclipse/sw360/antenna/
SCRIPT

$install = <<SCRIPT
set -ex
cd /bsinno-osm-antenna
./run_all_tests.sh --p2
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
    v.customize ["modifyvm", :id, "--memory", "4096"]
    v.customize ["modifyvm", :id, "--cpus", "2"]
    v.name = "tinaBox"
  end

  config.vm.network "forwarded_port", guest: 8000, host: 8000

  config.vm.provision "shell",
                      inline: $provision
  config.vm.provision "shell",
                      inline: $runCleanup,
                      run: "always",
                      privileged: false
  config.vm.synced_folder "..", "/bsinno-osm-antenna"
  config.vm.provision "shell",
                      inline: $install,
                      run: "always",
                      privileged: false
end

